on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Run Skaffold pipeline as command
        uses: hiberbee/github-action-skaffold@1.27.0
        id: build
        with:
          command: build --tag ${{ github.sha }}
          repository: ghcr.io/${{ github.repository_owner }}